version: "3.7"

networks:
  default:
    external:
      name: cloudbuild
  odoonet:

volumes:
  odoo-data:
  odoo-testlogs:
  odoo-modules:
  psql:

services:
  odoo:
    image: iterativodo/dockerdoo:${ODOO_VERSION}
    env_file: .env

    restart: unless-stopped

    ports: [ "8069:8069", "8072:8072" ]

    volumes:
      # Host paths (.ssh configuration)
      - ~/.ssh/:/opt/odoo/.ssh/:cached
      # Named volumes
      - odoo-data:${ODOO_DATA_DIR}
      - odoo-testlogs:${ODOO_LOGS_DIR}
      - odoo-modules:${ODOO_EXTRA_ADDONS}
    depends_on:
      - db

    networks:
      odoonet: # ------------------------
  db:
    image: postgres:${PSQL_VERSION}
    restart: unless-stopped
    volumes:
      - psql:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata

    networks:
      odoonet:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5454:5454/tcp
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mydomain.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_LISTEN_PORT=5454
    networks:
      odoonet:

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
    networks:
      odoonet: # ------------------------